name: Tests
description: Run auto tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Create env files
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}" >> .env
          echo "BETTER_AUTH_URL=${BETTER_AUTH_URL}" >> .env
          echo "BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}" >> .env

          echo "DATABASE_URL=${DATABASE_URL}" >> .dev.vars
          echo "DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}" >> .dev.vars
          echo "BETTER_AUTH_URL=${BETTER_AUTH_URL}" >> .dev.vars
          echo "BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}" >> .dev.vars

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - name: Run database migrations
        run: pnpm drizzle-kit push

      - name: Run tests
        run: pnpm test
